[ 
[ "Afghanistan", "AF" ],
[ "Albania", "AL" ],
[ "Algeria", "DZ" ],
[ "American Samoa", "AS" ],
[ "Andorra", "AD" ],
[ "Angola", "AO" ],
[ "Anguilla", "AI" ],
[ "Antarctica", "AQ" ],
[ "Antigua and Barbuda", "AG" ],
[ "Argentina", "AR" ],
[ "Armenia", "AM" ],
[ "Aruba", "AW" ],
[ "Australia", "AU" ],
[ "Austria", "AT" ],
[ "Azerbaijan", "AZ" ],
[ "Bahrain", "BH" ],
[ "Bangladesh", "BD" ],
[ "Barbados", "BB" ],
[ "Belarus", "BY" ],
[ "Belgium", "BE" ],
[ "Belize", "BZ" ],
[ "Benin", "BJ" ],
[ "Bermuda", "BM" ],
[ "Bhutan", "BT" ],
[ "Bolivia", "BO" ],
[ "Bosnia and Herzegovina", "BA" ],
[ "Botswana", "BW" ],
[ "Bouvet Island", "BV" ],
[ "Brazil", "BR" ],
[ "British Indian Ocean Territory", "IO" ],
[ "British Virgin Islands", "VG" ],
[ "Brunei", "BN" ],
[ "Bulgaria", "BG" ],
[ "Burkina Faso", "BF" ],
[ "Burundi", "BI" ],
[ "Côte d'Ivoire", "CI" ],
[ "Cambodia", "KH" ],
[ "Cameroon", "CM" ],
[ "Canada", "CA" ],
[ "Cape Verde", "CV" ],
[ "Cayman Islands", "KY" ],
[ "Central African Republic", "CF" ],
[ "Chad", "TD" ],
[ "Chile", "CL" ],
[ "China", "CN" ],
[ "Christmas Island", "CX" ],
[ "Cocos (Keeling) Islands", "CC" ],
[ "Colombia", "CO" ],
[ "Comoros", "KM" ],
[ "Congo", "CG" ],
[ "Cook Islands", "CK" ],
[ "Costa Rica", "CR" ],
[ "Croatia", "HR" ],
[ "Cuba", "CU" ],
[ "Cyprus", "CY" ],
[ "Czech Republic", "CZ" ],
[ "Democratic Republic of the Congo", "CD" ],
[ "Denmark", "DK" ],
[ "Djibouti", "DJ" ],
[ "Dominica", "DM" ],
[ "Dominican Republic", "DO" ],
[ "East Timor", "TL" ],
[ "Ecuador", "EC" ],
[ "Egypt", "EG" ],
[ "El Salvador", "SV" ],
[ "Equatorial Guinea", "GQ" ],
[ "Eritrea", "ER" ],
[ "Estonia", "EE" ],
[ "Ethiopia", "ET" ],
[ "Faeroe Islands", "FO" ],
[ "Falkland Islands", "FK" ],
[ "Fiji", "FJ" ],
[ "Finland", "FI" ],
[ "Former Yugoslav Republic of Macedonia", "MK" ],
[ "France", "FR" ],
[ "French Guiana", "GF" ],
[ "French Polynesia", "PF" ],
[ "French Southern Territories", "TF" ],
[ "Gabon", "GA" ],
[ "Georgia", "GE" ],
[ "Germany", "DE" ],
[ "Ghana", "GH" ],
[ "Gibraltar", "GI" ],
[ "Greece", "GR" ],
[ "Greenland", "GL" ],
[ "Grenada", "GD" ],
[ "Guadeloupe", "GP" ],
[ "Guam", "GU" ],
[ "Guatemala", "GT" ],
[ "Guinea", "GN" ],
[ "Guinea-Bissau", "GW" ],
[ "Guyana", "GY" ],
[ "Haiti", "HT" ],
[ "Heard Island and McDonald Islands", "HM" ],
[ "Honduras", "HN" ],
[ "Hong Kong", "HK" ],
[ "Hungary", "HU" ],
[ "Iceland", "IS" ],
[ "India", "IN" ],
[ "Indonesia", "ID" ],
[ "Iran", "IR" ],
[ "Iraq", "IQ" ],
[ "Ireland", "IE" ],
[ "Israel", "IL" ],
[ "Italy", "IT" ],
[ "Jamaica", "JM" ],
[ "Japan", "JP" ],
[ "Jordan", "JO" ],
[ "Kazakhstan", "KZ" ],
[ "Kenya", "KE" ],
[ "Kiribati", "KI" ],
[ "Kuwait", "KW" ],
[ "Kyrgyzstan", "KG" ],
[ "Laos", "LA" ],
[ "Latvia", "LV" ],
[ "Lebanon", "LB" ],
[ "Lesotho", "LS" ],
[ "Liberia", "LR" ],
[ "Libya", "LY" ],
[ "Liechtenstein", "LI" ],
[ "Lithuania", "LT" ],
[ "Luxembourg ", "LU" ],
[ "Macau", "MO" ],
[ "Madagascar", "MG" ],
[ "Malawi", "MW" ],
[ "Malaysia", "MY" ],
[ "Maldives", "MV" ],
[ "Mali", "ML" ],
[ "Malta", "MT" ],
[ "Marshall Islands", "MH" ],
[ "Martinique", "MQ" ],
[ "Mauritania", "MR" ],
[ "Mauritius", "MU" ],
[ "Mayotte", "YT" ],
[ "Mexico", "MX" ],
[ "Micronesia", "FM" ],
[ "Moldova", "MD" ],
[ "Monaco", "MC" ],
[ "Mongolia", "MN" ],
[ "Montserrat", "MS" ],
[ "Morocco", "MA" ],
[ "Mozambique", "MZ" ],
[ "Myanmar", "MM" ],
[ "Namibia", "NA" ],
[ "Nauru", "NR" ],
[ "Nepal", "NP" ],
[ "Netherlands", "NL" ],
[ "Netherlands Antilles", "AN" ],
[ "New Caledonia", "NC" ],
[ "New Zealand", "NZ" ],
[ "Nicaragua", "NI" ],
[ "Niger", "NE" ],
[ "Nigeria", "NG" ],
[ "Niue", "NU" ],
[ "Norfolk Island", "NF" ],
[ "North Korea", "KP" ],
[ "Northern Marianas", "MP" ],
[ "Norway", "NO" ],
[ "Oman", "OM" ],
[ "Pakistan", "PK" ],
[ "Palau", "PW" ],
[ "Panama", "PA" ],
[ "Papua New Guinea", "PG" ],
[ "Paraguay", "PY" ],
[ "Peru", "PE" ],
[ "Philippines", "PH" ],
[ "Pitcairn Islands", "PN" ],
[ "Poland", "PL" ],
[ "Portugal", "PT" ],
[ "Puerto Rico", "PR" ],
[ "Qatar", "QA" ],
[ "Réunion", "RE" ],
[ "Romania", "RO" ],
[ "Russia", "RU" ],
[ "Rwanda", "RW" ],
[ "São Tomé and Príncipe", "ST" ],
[ "Saint Helena", "SH" ],
[ "Saint Kitts and Nevis", "KN" ],
[ "Saint Lucia", "LC" ],
[ "Saint Pierre and Miquelon", "PM" ],
[ "Saint Vincent and the Grenadines", "VC" ],
[ "Samoa", "WS" ],
[ "San Marino", "SM" ],
[ "Saudi Arabia", "SA" ],
[ "Senegal", "SN" ],
[ "Seychelles", "SC" ],
[ "Sierra Leone", "SL" ],
[ "Singapore", "SG" ],
[ "Slovakia", "SK" ],
[ "Slovenia", "SI" ],
[ "Solomon Islands", "SB" ],
[ "Somalia", "SO" ],
[ "South Africa", "ZA" ],
[ "South Georgia and the South Sandwich Islands", "GS" ],
[ "South Korea", "KR" ],
[ "Spain", "ES" ],
[ "Sri Lanka", "LK" ],
[ "Sudan", "SD" ],
[ "Suriname", "SR" ],
[ "Svalbard and Jan Mayen", "SJ" ],
[ "Swaziland", "SZ" ],
[ "Sweden", "SE" ],
[ "Switzerland", "CH" ],
[ "Syria", "SY" ],
[ "Taiwan", "TW" ],
[ "Tajikistan", "TJ" ],
[ "Tanzania", "TZ" ],
[ "Thailand", "TH" ],
[ "The Bahamas", "BS" ],
[ "The Gambia", "GM" ],
[ "Togo", "TG" ],
[ "Tokelau", "TK" ],
[ "Tonga", "TO" ],
[ "Trinidad and Tobago", "TT" ],
[ "Tunisia", "TN" ],
[ "Turkey", "TR" ],
[ "Turkmenistan", "TM" ],
[ "Turks and Caicos Islands", "TC" ],
[ "Tuvalu", "TV" ],
[ "US Virgin Islands", "VI" ],
[ "Uganda", "UG" ],
[ "Ukraine", "UA" ],
[ "United Arab Emirates", "AE" ],
[ "United Kingdom", "GB" ],
[ "United States", "US" ],
[ "United States Minor Outlying Islands", "UM" ],
[ "Uruguay", "UY" ],
[ "Uzbekistan", "UZ" ],
[ "Vanuatu", "VU" ],
[ "Vatican City", "VA" ],
[ "Venezuela", "VE" ],
[ "Vietnam", "VN" ],
[ "Wallis and Futuna", "WF" ],
[ "Western Sahara", "EH" ],
[ "Yemen", "YE" ],
[ "Yugoslavia", "YU" ],
[ "Zambia", "ZM" ],
[ "Zimbabwe", "ZW" ]
]
